# Generated by Django 3.1.6 on 2021-02-05 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_transcao'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transcao',
            new_name='Transacao',
        ),
    ]
